Repository Team-MeetGo/MeetGO, pull requests merged in 2024-04, with the labels that each got.

#13 [feat] - 리뷰 쓰는 모달 만들기 및 등록된 리뷰 불러오기
  next.config.mjs
  package.json
  postcss.config.js
  src/app/layout.tsx
  src/app/review/page.tsx
  src/components/review/ModalPortal.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewList.tsx
  src/components/review/ReviewModal.tsx
  src/components/review/test.ts
  src/utils/supabase/client.ts
  yarn.lock
Labels: documentation, enhancement, 유진

#14 황인정-[feat]: NextUI 초기설정
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/app/provider/NextUIProvider.tsx
  src/app/provider/QueryProvider.tsx
  src/middleware.ts
  src/store/userStore.ts
  src/utils/supabase/client.ts
  tailwind.config.ts
Labels: 인정

#20 이혜진-[feat] meetingroom 리스트 불러오기 기능 구현
  src/app/meetingRoom/page.tsx
  src/app/page.tsx
  src/components/room/MeetingRoom.tsx
  src/components/room/MeetingRoomList.tsx
  src/hooks/custom/room.ts
Labels: 혜진

#23 [feat] - 리뷰 상세페이지 만들기, 댓글 등록 및 불러오기
  src/app/layout.tsx
  src/app/review/[review_id]/page.tsx
  src/components/review/ModalPortal.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewList.tsx
  src/components/review/ReviewModal.tsx
  src/components/review/comment/CommentList.tsx
  src/components/review/comment/NewComment.tsx
  src/types/database.types.ts
Labels: documentation, enhancement, 유진

#24 이혜진 - [feat] meetingroom 삭제하기
  src/components/room/DeleteMeetingRoom.tsx
  src/components/room/EditMeetingRoom.tsx
  src/components/room/MeetingRoom.tsx
  src/types/database.types.ts
Labels: 혜진

#29 최희라 - [feat] : 회원가입, 로그인 기능 구현 및 스타일링 완료
  .github/pull_request_template.md
  .vscode/settings.json
  src/app/auth/callback/route.ts
  src/app/globals.css
  src/app/users/join/page.tsx
  src/app/users/login/page.tsx
  src/components/user/JoinForm.tsx
  src/components/user/LoginForm.tsx
  src/components/user/test.ts
  src/utils/api/authAPI.ts
Labels: 희라

#36 최희라 - [feat] : 회원가입, 로그인 유효성 검사 및 모달창 구현 완료
  src/app/chat/page.tsx
  src/app/globals.css
  src/app/users/join/page.tsx
  src/app/users/login/page.tsx
  src/components/common/ValidationModal.tsx
  src/components/user/JoinForm.tsx
  src/components/user/LoginForm.tsx
  src/store/modalStore.ts
  src/types/modalTypes.ts
  src/types/userTypes.ts
  src/utils/api/authAPI.ts
  src/utils/authValidation.ts
Labels: 희라

#44 이혜진 - [feat/#42] - 수락창의 인원수 달성시 채팅방으로 가는 버튼 활성화
  src/app/meetingRoom/[id]/page.tsx
  src/components/room/MeetingRoomForm.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RealTimeSubscription.tsx
  src/hooks/custom/participants.ts
Labels: 혜진

#52 최희라 - [feat] : 프로필 수정 기능 구현
  src/app/chat/page.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/components/navBar/NavBar.tsx
  src/components/user/JoinForm.tsx
  src/components/user/LoginForm.tsx
  src/middleware.ts
  src/store/userStore.ts
  src/types/userTypes.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: 희라

#55 최희라 - [Feat] : 프로필 데이터 세팅 및 수정 구현
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/store/userStore.ts
  src/types/database.types.ts
  src/utils/FavoriteData.tsx
Labels: 희라

#56 이혜진 - [feat] - 수락창에 입장한 유저 정보 배열하기
  src/app/meetingRoom/[id]/page.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
  src/hooks/custom/participants.ts
  src/types/database.types.ts
Labels: 혜진

#67 양유진 - [feat/#64] - 리뷰 좋아요 관련 기능 수정, 사진 업로드 관련 기능 수정
  .env
  src/app/page.tsx
  src/app/review/pageNumber/[pageNumber]/page.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewComment.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewEditModal.tsx
  src/components/review/ReviewHeart.tsx
  src/components/review/ReviewList.tsx
  src/components/review/comment/CommentCard.tsx
  src/components/review/comment/CommentList.tsx
  src/components/review/comment/NewComment.tsx
  src/types/database.types.ts
  src/utils/icons/HeartFillIcon.tsx
  src/utils/icons/HeartIcon.tsx
Labels: documentation, enhancement, 유진

#70 양유진 - [feat/#68] - 로그인 상태에서만 리뷰 등록 버튼이 보이게 수정
  src/app/review/pageNumber/[pageNumber]/page.tsx
Labels: bug, documentation

#72 최희라 - [feat] : 마이페이지 코드 리팩토링 및 Navbar 추가
  src/app/layout.tsx
  src/components/common/NavBar.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/MetPeople.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/components/navBar/NavBar.tsx
  src/utils/FavoriteData.tsx
  src/utils/icons/meetgo-logo.png
Labels: 희라

#79 이혜진 - feat/#74: 유저가 참여중인 방 최상단에 위치
  src/components/room/MeetingRoomList.tsx
  src/hooks/custom/room.ts
Labels: 혜진

#84 신서연 - [feat]: 미팅 시간, 장소 선택 구현
  .env
  src/app/chat/[chatroom_id]/page.tsx
  src/app/chat/page.tsx
  src/components/chat/sidebar/DatePicker.tsx
  src/components/chat/sidebar/Map.tsx
  src/components/chat/sidebar/SideBar.tsx
  src/components/room/MeetingRoom.tsx
Labels: 서연

#88 양유진 - [feat/#87] - zustand로 유저 정보 불러오기, 로그인 상태 관리, 댓글 crud 관리
  .env
  src/app/page.tsx
  src/app/review/pageNumber/[pageNumber]/page.tsx
  src/components/mypage/MyPost.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewComment.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewEditModal.tsx
  src/components/review/ReviewHeart.tsx
  src/components/review/ReviewList.tsx
  src/components/review/comment/CommentCard.tsx
  src/components/review/comment/CommentList.tsx
  src/components/review/comment/NewComment.tsx
  src/store/commentStore.ts
Labels: bug, documentation, enhancement, 유진

#90 이혜진 - feat: 방장이 방 나가면 방 리더를 다른 멤버에게 승계
  src/components/room/MeetingRoomForm.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
Labels: 혜진

#98 양유진 - [feat/#96] - review페이지 이동 시 경로를 reivew/pageNumber/1로 바꾸기
  src/app/page.tsx
  src/components/common/NavBarContents.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewHeart.tsx
Labels: documentation, enhancement, 유진

#102 황인정 - [feat]: 로그인/로그아웃 시 navBar 상태 즉시 변경
  src/components/common/NavBar.tsx
  src/components/common/NavBarContents.tsx
  src/components/user/InitUser.tsx
  src/components/user/LoginForm.tsx
  src/middleware/chatRouteHandler.ts
  src/store/userStore.ts
Labels: 인정

#116 황인정 - [feat]: tanstack-query로 변경(meetingRoom 데이터)
  src/components/chat/chatBody/ChatList.tsx
  src/components/chat/chatBody/OthersChat.tsx
  src/components/chat/chatHeader/ChatParticipants.tsx
  src/components/room/MeetingRoomList.tsx
  src/hooks/useQueries/useChattingQuery.ts
  src/hooks/useQueries/useMeetingQuery.ts
  src/query/chat/chatQueryFns.ts
  src/query/chat/chatQueryKeys.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/query/meetingRoom/meetingQueryKeys.ts
  src/services/queryFns.ts
  src/services/queryKeys.ts
  src/store/chatStore.ts
Labels: 인정

#119 양유진 - [feat/#118] - query사용하여 리뷰 정보 불러오기, 리뷰 작성시 닉네임 공개여부 기능 추가
  src/app/page.tsx
  src/app/review/pageNumber/[pageNumber]/page.tsx
  src/components/mainpage/getMostLikedReview.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewEditModal.tsx
  src/components/review/ReviewHeart.tsx
  src/components/review/ReviewList.tsx
  src/query/review/reviewQueryFns.ts
  src/query/review/reviewQueryKeys.ts
  src/types/database.types.ts
Labels: documentation, enhancement, 유진

#120 황인정- [feat]: queryFn 수정
  src/app/meetingRoom/[id]/page.tsx
  src/components/chat/chatBody/ChatList.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/user/InitUser.tsx
  src/hooks/useQueries/useChattingQuery.ts
  src/hooks/useQueries/useMeetingQuery.ts
  src/middleware/chatRouteHandler.ts
  src/query/chat/chatQueryFns.ts
  src/query/chat/chatQueryKeys.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/query/meetingRoom/meetingQueryKeys.ts
  src/store/chatStore.ts
Labels: 인정

#125 최희라 - [feat] : 카카오톡 ID 요청하기 로직 구현 (아직 실시간X 새로고침해야 반영되는 방식)
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MetPeople.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/hooks/useMutation/test.ts
  src/hooks/useMutation/useMetPeopleMutation.ts
  src/hooks/useQueries/test.ts
  src/hooks/useQueries/useMetPeople.ts
  src/query/user/metPeopleQueryFns.ts
  src/query/user/metPeopleQueryKeys.ts
  src/service/index.ts
  src/types/database.types.ts
  tailwind.config.ts
Labels: 희라

#127 황인정 - [fix]: 미들웨어(채팅창)
  src/app/meetingRoom/page.tsx
  src/app/test/page.tsx
  src/components/chat/Test.tsx
  src/components/chat/chatBody/ChatList.tsx
  src/components/room/MeetingRoom.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/RoomInformation.tsx
  src/hooks/useQueries/useMeetingQuery.ts
  src/middleware/chatRouteHandler.ts
  src/middleware/routeHandlerMiddleware.ts
  src/query/chat/chatQueryFns.ts
  src/query/meetingRoom/meetingQueryFns.ts
Labels: 인정

#129 이혜진 - refactor: 리엑트 쿼리로 변환
  src/app/meetingRoom/(lobby)/page.tsx
  src/app/meetingRoom/[id]/page.tsx
  src/app/meetingRoom/page.tsx
  src/components/room/DeleteMeetingRoom.tsx
  src/components/room/EditMeetingRoom.tsx
  src/components/room/MeetingRoom.tsx
  src/components/room/MeetingRoomFeatureTags.tsx
  src/components/room/MeetingRoomForm.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
  src/hooks/custom/participants.ts
  src/hooks/custom/room.ts
  src/hooks/useMutation/useMeetingMutation.ts
  src/hooks/useQueries/useMeetingQuery.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/query/meetingRoom/meetingQueryKeys.ts
  src/types/roomTypes.ts
Labels: 혜진

#130 이혜진 - feat: 내가 참여한 방 화살표로 좌우로 이동, 새로고침 기능
  src/app/meetingRoom/[id]/page.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
Labels: 혜진

#135 최희라 - [Refactor] : user데이터 쿼리로 불러오기
  .vscode/settings.json
  package.json
  src/components/common/NavBar.tsx
  src/components/common/NavBarContents.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MetPeople.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/components/mypage/Test.tsx
  src/components/user/InitUser.tsx
  src/hooks/custom/test.ts
  src/hooks/custom/useInputChange.tsx
  src/hooks/useQueries/useMetPeopleQuery.ts
  src/hooks/useQueries/useUserQuery.ts
  src/query/user/userQueryFns.ts
  src/query/user/userQueryKeys.ts
  src/store/userStore.ts
  yarn.lock
Labels: 희라

#137 양유진 - [feat/#136] - query사용하여 데이터 가져오기
  src/app/review/[review_id]/page.tsx
  src/components/mainpage/getMostLikedReview.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewHeart.tsx
  src/components/review/ReviewList.tsx
  src/components/review/comment/CommentCard.tsx
  src/components/review/comment/CommentList.tsx
  src/components/review/comment/NewComment.tsx
  src/query/review/commentQueryFns.ts
  src/query/review/commentQueryKeys.ts
  src/query/review/reviewQueryFns.ts
  src/query/review/reviewQueryKeys.ts
Labels: documentation, enhancement, 유진

#138 신서연 - [style] : 사이드 바 디자인
  package.json
  src/app/globals.css
  src/components/chat/sidebar/DateCustomeInput.tsx
  src/components/chat/sidebar/DatePicker.tsx
  src/components/chat/sidebar/DateTimePicker.tsx
  src/components/chat/sidebar/Map.tsx
  src/components/chat/sidebar/SideBar.tsx
  yarn.lock
Labels: 서연

#140 이혜진 - feat: 지역과 인원수 필터링, 뒤로가기 누르면 데이터베이스에서 유저 정보 제거
  src/app/meetingRoom/(lobby)/page.tsx
  src/app/meetingRoom/[id]/page.tsx
  src/components/room/EditMeetingRoom.tsx
  src/components/room/MeetingRoomFeatureTags.tsx
  src/components/room/MeetingRoomForm.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/MemberNumberSelection.tsx
  src/components/room/RegionSelection.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
  src/hooks/useMutation/useMeetingMutation.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/store/roomStore.ts
  src/store/searchRoomStore.ts
  src/types/database.types.ts
  src/utils/MeetingRoomSelector.tsx
Labels: 혜진

#142 최희라 - [fix] : 유저정보쿼리 수정하여 적용 (store => query)
  src/components/common/NavBarContents.tsx
  src/components/mainpage/getMostLikedReview.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MetPeople.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/user/LoginForm.tsx
  src/hooks/useMutation/useProfileMutation.ts
  src/hooks/useQueries/useUserQuery.ts
  src/query/user/metPeopleQueryFns.ts
  src/query/user/userQueryFns.ts
  src/service/index.ts
  src/types/userTypes.ts
Labels: 희라

#147 [refactor] - 리뷰 수정 시 query 사용, 댓글 관련 코드에서 zustand 삭제, query hooks 정리
  src/app/review/[review_id]/page.tsx
  src/components/mainpage/getMostLikedReview.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewComment.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewEditModal.tsx
  src/components/review/ReviewLike.tsx
  src/components/review/ReviewList.tsx
  src/components/review/comment/CommentCard.tsx
  src/components/review/comment/CommentList.tsx
  src/components/review/comment/NewComment.tsx
  src/hooks/useMutation/useCommentMutations.ts
  src/hooks/useMutation/useLikeMutation.ts
  src/hooks/useMutation/useReviewMutations.ts
  src/hooks/useQueries/useCommentQuery.ts
  src/hooks/useQueries/useLikeQuery.ts
  src/hooks/useQueries/useReviewQuery.ts
  src/query/review/commentQueryFns.ts
  src/query/review/commentQueryKeys.ts
  src/query/review/likeQueryFns.ts
  src/query/review/reviewQueryFns.ts
  src/query/review/reviewQueryKeys.ts
  src/store/commentStore.ts
  src/utils/icons/HeartIcon.tsx
Labels: documentation, 유진

#149 최희라 - [feat] : Navbar 페이지 이동시 깜빡임 해결
  src/app/globals.css
  src/app/users/join/page.tsx
  src/app/users/login/page.tsx
  src/components/common/NavBarContents.tsx
  src/components/common/RouteButton.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MetPeople.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/components/user/JoinForm.tsx
  src/components/user/LoginForm.tsx
  src/query/user/userQueryFns.ts
  src/service/index.ts
Labels: 희라

#156 황인정- [feat]: middleware를 통한 인증/인가
  src/app/chat/[chatroom_id]/page.tsx
  src/components/chat/chatBody/OthersChat.tsx
  src/components/common/NavBarContents.tsx
  src/middleware.ts
  src/middleware/chatRouteHandler.ts
  src/middleware/meetingNChatRouteHandler.ts
  src/middleware/routeHandlerMiddleware.ts
Labels: 인정

#157 최희라 - [style] : 마이페이지 UI 1차 구현
  .vscode/settings.json
  src/components/common/NavBarContents.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/components/user/LoginForm.tsx
  src/hooks/useMutation/useProfileMutation.ts
  src/hooks/useMutation/useSchoolMutation.ts
  src/hooks/useQueries/useUserQuery.ts
  src/query/user/userQueryFns.ts
  src/query/user/userQueryKeys.ts
  src/service/index.ts
  src/types/database.types.ts
  src/utils/icons/login_kakao.png
  src/utils/icons/logo_google.png
Labels: 희라

#158 최희라 - [feat] : 학교 인증 모달창으로 변경
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/MetPeople.tsx
  src/components/mypage/MyPost.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/hooks/useMutation/useProfileMutation.ts
  src/hooks/useQueries/useUserQuery.ts
  src/query/user/metPeopleQueryFns.ts
  src/types/userTypes.ts
Labels: 희라

#162 양유진 - [style] - 메인페이지, 리뷰 페이지 ui 구현
  public/mainbanner_flower.png
  public/mainbanner_people.png
  src/app/page.tsx
  src/app/review/[review_id]/page.tsx
  src/app/review/pageNumber/[pageNumber]/page.tsx
  src/components/mainpage/getMostLikedReview.tsx
  src/components/review/ImageGallery.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewComment.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewDetailNavigate.tsx
  src/components/review/ReviewEditModal.tsx
  src/components/review/ReviewLike.tsx
  src/components/review/ReviewList.tsx
  src/components/review/comment/CommentCard.tsx
  src/components/review/comment/CommentList.tsx
  src/components/review/comment/NewComment.tsx
  src/hooks/custom/useReviewNavigation.ts
  src/hooks/useQueries/useReviewQuery.ts
  src/utils/icons/AvatarDefault.tsx
  tailwind.config.ts
Labels: documentation, enhancement, 유진

#171 최희라 - fix : 로그인, 회원가입 주소 변경
  src/components/common/NavBarContents.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/user/LoginForm.tsx
Labels: 희라

#173 최희라 - [fix] : 카카오ID요청 상대프로필사진 이미지 비율맞게 들어오도록 조정
  src/components/mypage/MetPeople.tsx
Labels: 희라

#175 Feat acceptanceroom/#141
  src/app/meetingRoom/(lobby)/page.tsx
  src/app/meetingRoom/[id]/page.tsx
  src/components/room/DeleteMeetingRoom.tsx
  src/components/room/MeetingRoom.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
  src/hooks/useMutation/useMeetingMutation.ts
  src/hooks/useQueries/useMeetingQuery.ts
  src/query/meetingRoom/meetingQueryFns.ts
Labels: 혜진

#201 이혜진 - feat: 버튼을 방장만 볼 수 있게 + 실시간 연동
  src/components/chat/ChatLoading.tsx
  src/components/chat/chatHeader/ChatHeader.tsx
  src/components/room/DeleteMeetingRoom.tsx
  src/components/room/EditMeetingRoom.tsx
  src/components/room/MeetingRoom.tsx
  src/components/room/MeetingRoomForm.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/MemberNumberSelection.tsx
  src/components/room/RegionSelection.tsx
  src/components/room/participants/AcceptanceRoomButtons.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
  src/hooks/custom/room.ts
  src/hooks/useMutation/useMeetingMutation.ts
  src/hooks/useQueries/useMeetingQuery.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/utils/icons/RoomAvatar.tsx
  src/utils/icons/meetgo-logo-purple.png
  tailwind.config.ts
  yarn.lock
Labels: 혜진

#207 이혜진 - feat: 쿼리로 새로고침
  src/app/meetingRoom/[id]/page.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/participants/Member.tsx
  src/hooks/useQueries/useMeetingQuery.ts
Labels: 혜진

#215 이혜진 - refactor: 코드리뷰에 따른 코드 정리
  .vscode/settings.json
  package.json
  src/app/(auth)/join/page.tsx
  src/app/meetingRoom/(lobby)/page.tsx
  src/app/meetingRoom/[id]/page.tsx
  src/components/chat/chatBody/ChatList.tsx
  src/components/common/InitChatRealTime.tsx
  src/components/common/NavBarContents.tsx
  src/components/mypage/MetPeople.tsx
  src/components/room/DeleteMeetingRoom.tsx
  src/components/room/EditMeetingRoom.tsx
  src/components/room/MeetingRoom.tsx
  src/components/room/MeetingRoomForm.tsx
  src/components/room/MeetingRoomList.tsx
  src/components/room/RegionSelection.tsx
  src/components/room/RoomLoading.tsx
  src/components/room/lobby/MeetingRoomList.tsx
  src/components/room/lobby/MyRoomTitle.tsx
  src/components/room/lobby/OtherRoomsTitle.tsx
  src/components/room/lobby/RefreshButton.tsx
  src/components/room/participants/AcceptanceRoom.tsx
  src/components/room/participants/GotoChatButton.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
  src/components/room/singleMeetingRoom/MeetingRoom.tsx
  src/components/room/singleMeetingRoom/RoomInformation.tsx
  src/components/user/JoinForm.tsx
  src/components/user/LoginForm.tsx
  src/components/user/ResetPasswordForm.tsx
  src/hooks/useQueries/useMeetingQuery.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/types/roomTypes.ts
  src/types/userTypes.ts
  src/utils/icons/RoomAvatar.tsx
  yarn.lock
Labels: 혜진

#219 황인정 - [fix]: 코드리뷰에 따른 수정
  src/components/chat/chatBody/ChatDeleteDropDown.tsx
  src/hooks/useQueries/useChattingQuery.ts
  src/middleware.ts
  src/middleware/chatRouteHandler.ts
  src/middleware/meetingNChatRouteHandler.ts
  src/middleware/meetingRoomRounteHandler.ts
  src/middleware/schoolValidateMiddleware.ts
  tsconfig.json
Labels: 인정

#222 황인정 - [fix]: 불필요한 주석 제거
  src/components/chat/chatBody/ChatDeleteDropDown.tsx
  src/components/chat/chatBody/ChatImg.tsx
  src/components/chat/chatHeader/ChatPresence.tsx
  src/components/chat/chatHeader/InitChat.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Test.tsx
  src/components/review/ReviewDetailNavigate.tsx
  src/components/room/participants/Member.tsx
  src/components/user/ResetPasswordForm.tsx
  src/query/chat/chatQueryFns.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/query/review/commentQueryFns.ts
  src/service/index.ts
  src/service/sidebar/index.ts
  src/utils/api/authAPI.ts
Labels: 인정

#225 황인정: [fix] - 채팅 코드리뷰 후 수정
  src/components/chat/chatBody/ChatImg.tsx
  src/components/chat/chatBody/ChatList.tsx
  src/components/chat/chatBody/MyChat.tsx
  src/components/chat/chatBody/MyInfoWrapper.tsx
  src/components/chat/chatBody/OthersChat.tsx
  src/components/chat/chatBody/ParticipantsInfoWrapper.tsx
  src/components/chat/chatBody/ShowChatMember.tsx
  src/components/chat/chatFooter/ChatInput.tsx
  src/components/chat/chatFooter/RememberLastChat.tsx
  src/components/chat/chatHeader/ChatHeader.tsx
  src/components/chat/chatHeader/ChatPresence.tsx
  src/components/chat/chatHeader/InitChat.tsx
  src/components/chat/sidebar/DateTimePicker.tsx
  src/components/chat/sidebar/Map.tsx
  src/components/chat/sidebar/SideBar.tsx
  src/hooks/useQueries/useChattingQuery.ts
  src/middleware/routeHandlerMiddleware.ts
  src/query/chat/chatQueryFns.ts
  src/types/roomTypes.ts
  yarn.lock
Labels: 인정

#228 황인정: [fix] - 미팅 날짜 Realtime 오류 수정
  package.json
  src/app/chat/[chatroom_id]/page.tsx
  src/app/mypage/page.tsx
  src/app/provider/QueryProvider.tsx
  src/components/chat/chatBody/ChatDeleteDropDown.tsx
  src/components/chat/chatBody/ChatImg.tsx
  src/components/chat/chatBody/ChatList.tsx
  src/components/chat/chatBody/MyChat.tsx
  src/components/chat/chatBody/MyInfoWrapper.tsx
  src/components/chat/chatBody/OthersChat.tsx
  src/components/chat/chatBody/ParticipantsInfoWrapper.tsx
  src/components/chat/chatBody/ShowChatMember.tsx
  src/components/chat/chatFooter/ChatInput.tsx
  src/components/chat/chatFooter/RememberLastChat.tsx
  src/components/chat/chatHeader/ChatHeader.tsx
  src/components/chat/chatHeader/ChatPresence.tsx
  src/components/chat/chatHeader/InitChat.tsx
  src/components/chat/sidebar/DateCustomeInput.tsx
  src/components/chat/sidebar/DateTimePicker.tsx
  src/components/chat/sidebar/Map.tsx
  src/components/chat/sidebar/SideBar.tsx
  src/components/common/NavBarContents.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/Favorite.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileHeader.tsx
  src/components/mypage/Test.tsx
  src/components/review/ReviewDetailNavigate.tsx
  src/components/room/MeetingRoomForm.tsx
  src/components/room/participants/Member.tsx
  src/components/room/singleMeetingRoom/MeetingRoom.tsx
  src/components/user/JoinForm.tsx
  src/components/user/LoginForm.tsx
  src/components/user/ResetPasswordForm.tsx
  src/hooks/useMutation/useSchoolMutation.ts
  src/hooks/useQueries/useChattingQuery.ts
  src/hooks/useQueries/useUserQuery.ts
  src/middleware/routeHandlerMiddleware.ts
  src/query/chat/chatQueryFns.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/query/review/commentQueryFns.ts
  src/query/user/userQueryKeys.ts
  src/service/index.ts
  src/service/sidebar/index.ts
  src/store/modalStore.ts
  src/store/userStore.ts
  src/types/roomTypes.ts
  src/utils/api/authAPI.ts
  yarn.lock
Labels: 인정

#240 이혜진 - feat: 참여한 방이 없을 때 UI 변경
  src/app/meetingRoom/(lobby)/page.tsx
  src/app/page.tsx
  src/components/chat/chatHeader/InitChat.tsx
  src/components/chat/sidebar/DateTimePicker.tsx
  src/components/chat/sidebar/Map.tsx
  src/components/common/NavBarContents.tsx
  src/components/common/ValidationModal.tsx
  src/components/common/customToast.tsx
  src/components/mainpage/ProfileRouteModal.tsx
  src/components/mypage/AvatarForm.tsx
  src/components/mypage/MetPeople.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SchoolForm.tsx
  src/components/room/InitRoom.tsx
  src/components/room/LobbySkeleton.tsx
  src/components/room/MeetingRoomForm.tsx
  src/components/room/RoomLoading.tsx
  src/components/room/lobby/MeetingRoomList.tsx
  src/components/room/lobby/MyRoomTitle.tsx
  src/components/room/participants/GotoChatButton.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
  src/components/room/singleMeetingRoom/MeetingRoom.tsx
  src/components/user/LoginForm.tsx
  src/hooks/useMutation/useFirstLoginMutation.ts
  src/hooks/useMutation/useMeetingLocationMutation.ts
  src/hooks/useMutation/useMeetingMutation.ts
  src/hooks/useMutation/useMetPeopleMutation.ts
  src/hooks/useQueries/useMeetingQuery.ts
  src/hooks/useQueries/useUserQuery.ts
  src/middleware.ts
  src/query/chat/chatQueryFns.ts
  src/query/meetingRoom/meetingQueryFns.ts
  src/query/meetingRoom/meetingQueryKeys.ts
  src/query/review/reviewQueryFns.ts
  src/service/index.ts
  src/store/modalStore.ts
  src/store/sideBarStore.ts
  src/types/database.types.ts
  src/types/modalTypes.ts
  src/utils/api/authAPI.ts
Labels: 혜진

#244 이혜진 - [fix] : 채팅으로 가는 버튼의 디자인 및 어구 변경
  src/components/room/lobby/MeetingRoomList.tsx
  src/components/room/participants/GotoChatButton.tsx
  src/components/room/participants/HollowFemaleMemberCard.tsx
  src/components/room/participants/HollowMaleMemberCard.tsx
  src/components/room/participants/Member.tsx
  src/components/room/participants/RoomInformation.tsx
  src/components/room/singleMeetingRoom/MeetingRoom.tsx
  src/components/room/singleMeetingRoom/RoomInformation.tsx
  src/hooks/custom/useGenderMaxNumber.ts
  src/hooks/custom/useUserHook.tsx
  src/hooks/useMutation/useMeetingMutation.ts
Labels: 혜진

#245 이혜진 - [feat] : 로비에 스켈레톤 만들기
  src/components/room/LobbySkeleton.tsx
  src/hooks/useMutation/useMeetingMutation.ts
Labels: 혜진

#250 신서연 : [Refactor] - 리팩토링
  public/mainbanner-2.jpg
  public/mainbanner-3.jpg
  src/app/globals.css
  src/app/page.tsx
  src/app/review/[review_id]/page.tsx
  src/components/chat/sidebar/DateCustomeInput.tsx
  src/components/chat/sidebar/DateTimePicker.tsx
  src/components/chat/sidebar/Map.tsx
  src/components/chat/sidebar/SideBar.tsx
  src/components/chat/sidebar/SideBarButton.tsx
  src/components/common/NavBarContents.tsx
  src/components/common/ValidationModal.tsx
  src/components/mainpage/GetMostLikedReview.tsx
  src/components/mainpage/ProfileRouteModal.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileHeader.tsx
  src/components/review/ImageGallery.tsx
  src/components/review/NewReview.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewDetail.tsx
  src/components/review/ReviewEditModal.tsx
  src/components/review/ReviewLike.tsx
  src/components/review/ReviewList.tsx
  src/components/review/comment/CommentCard.tsx
  src/components/review/comment/NewComment.tsx
  src/components/user/JoinForm.tsx
  src/components/user/ResetPasswordForm.tsx
  src/hooks/useMutation/useMeetingTimeMutation.ts
  src/hooks/useMutation/useReviewMutations.ts
  src/query/chat/chatQueryFns.ts
  src/query/review/commentQueryFns.ts
  src/types/sideBarTypes.ts
  src/types/userTypes.ts
  src/utils/Validation.ts
  src/utils/constant.ts
  src/utils/index.ts
  tailwind.config.ts
Labels: 서연

#253 신서연 : [Refactor] - alert창, 장소선택 오류 수정
  src/components/chat/sidebar/DateCustomeInput.tsx
  src/components/chat/sidebar/DateTimePicker.tsx
  src/components/chat/sidebar/Map.tsx
  src/components/chat/sidebar/SideBar.tsx
Labels: 서연
